
services:
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: pxy_site_strapi
    restart: always
    env_file:
      - ./packages/backend/.env
    environment:
      NODE_ENV: production
      LOG_LEVEL: debug
    ports:
      - '1337:1337'
    volumes:
      - ./packages/backend/storage/uploads:/app/packages/backend/public/uploads

volumes: {}
